Feature/add score component
NDLANO/h5p-three-image pull request #28
Opened 2021-06-01 13:21 UTC by kentis

2021-06-01 13:26 UTC, boyum commented on scripts/components/Dialog/SceneScores.js
> +        {/* <tr><td>Total</td><td>{totalScore}</td></tr> */}
?

2021-06-01 13:34 UTC, boyum commented on scripts/components/Main.js
> +          // Noop
`H5P.libraryFromString` will parse the library name and give the library's machine name. Using the machine name only, we don't have to update the version numbers later:


```suggestion
      const libraryName = H5P.libraryFromString(interaction.action.library).machineName;
      switch(libraryName) {
        case "H5P.Summary":
          sceneScoreCard[i]={title: interaction.label.labelText, raw: 0, max: 1, scaled: 0};
          break;
        case "H5P.SingleChoiceSet":
          sceneScoreCard[i]={title: interaction.label.labelText, raw: 0, max: interaction.action.params.choices.length, scaled: 0};
          break;
        default:
          // Noop
```

2021-06-01 13:37 UTC, boyum commented on semantics.json
> +      {
When adding fields to semantics.json, remember to add these fields in the right places in every language file as well. Only `label` and `description` properties are needed in the language files.

2021-06-01 13:38 UTC, boyum commented on stories/static/three.min.js
> +      a};this.setFrameOfReferenceType=function(a){q=a};this.setSession=function(b){h=b;null!==h&&(h.addEventListener("select",c),h.addEventListener("selectstart",c),h.addEventListener("selectend",c),
?

```suggestion
      a};this.setFrameOfReferenceType=function(a){q=a};this.setSession=function(b){h=b;null!==h&&(h.addEventListener("select",c),h.addEventListener("selectstart",c),h.addEventListener("selectend",c),h.addEventListener("end",d),h.baseLayer=new XRWebGLLayer(h,f,{framebufferScaleFactor:k}),h.requestFrameOfReference(q).then(function(b){m=b;a.setFramebuffer(h.baseLayer.framebuffer);v.setContext(h);v.start()}),l=h.getInputSources(),h.addEventListener("inputsourceschange",function(){l=h.getInputSources();
```

2021-06-10 09:02 UTC, boyum commented on scripts/components/Dialog/SceneScores.js
> +        {/* <tr><td>Total</td><td>{totalScore}</td></tr> */}
```suggestion
```

2021-06-10 09:04 UTC, boyum commented on scripts/components/Dialog/ScoreSummary.js
> +    const totalScores = this.getToalScores(this.props.scores);
```suggestion
  getTotalScores(scores){
    const totalScores = {score: 0, max:0};
    for(const scene in this.context.params.scenes){
      const sceneScores = scores[scene];
      for(const [id, score] of Object.entries(sceneScores)){
        if(id !== "title") {
          totalScores.score += score.raw;
          totalScores.max += score.max;  
        }
      }
    }
    return totalScores;
  }
  
  render() {
    const items = []
    const totalScores = this.getTotalScores(this.props.scores);
```

2021-06-10 09:06 UTC, boyum commented on scripts/components/Dialog/SceneScores.js
> +    return `Scene: ${sceneId}`
Should these be translated?

2021-06-10 09:07 UTC, boyum commented on scripts/components/Main.js
> +          // Noop
Why was this resolved?

2021-06-10 13:59 UTC, kentis commented on scripts/components/Dialog/SceneScores.js
> +    return `Scene: ${sceneId}`
yes

2021-06-11 06:00 UTC, boyum approved these changes

2021-06-11 06:03 UTC, boyum requested changes
Waaait let me just test

2021-06-11 08:37 UTC, boyum approved these changes

2021-06-11 09:34 UTC, merged